### PR TITLE
feat(web): Added functions to confirm user and get user attributes

### PR DESCRIPTION
**Pull request by fahadsadiq**
*Description of changes:*
Added function to confirm sign up and get user attributes.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ottokruse** [comment]
To fix prettier issues, run this in the root of the workspace:

`npx prettier -w .`

**Comment by fahadsadiq** [comment]
The reason is that we are using this lib server side on svelte. We wanted to use cookies and it became a bit difficult to set and get those cookies.

So we wanted to pass the token as a param instead.

**Comment by ottokruse** [comment]
Got it, understood, and thanks for the explanation.

Cool to hear you use this in Svelte on server side! Let us know any feedback you have to make life easier for that (such as more docs maybe ...)

See prettier is still failing. Make sure you have the exact same version as the lib? Should be 3.1.1

**Comment by ottokruse** [comment]
THANKS!

**Comment by ottokruse** [comment]
Published to NPM in v0.13.0

**Pull request merged**
