### PR TITLE
Remove return types from getUser as they were not correct.

### PR DESCRIPTION
**Pull request by fahadsadiq**
*Issue #, if available:*

Another oversight from my side. Apologies. I have tested this end to end and it works fine.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ottokruse** [comment]
Hey mate can we instead of removing it just change the type to what it needs to be? Should be easy, can almost copy it verbatim from [the docs](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUser.html)

**Comment by fahadsadiq** [comment]
Done

**Comment by ottokruse** [comment]
Lat req, can you tweak it to this, otherwise TS might do funny and understand the lists to be fixed size:

```ts
interface GetUserResponse {
  MFAOptions: {
      AttributeName: string;
      DeliveryMedium: string;
    }[];
  PreferredMfaSetting: string;
  UserAttributes:  {
      Name: string;
      Value: string;
    }[];
  UserMFASettingList: string[];
  Username: string;
}
```


THANKS

**Comment by fahadsadiq** [comment]
Updated.

**Comment by ottokruse** [comment]
Hey mate you added the type to the wrong function, to `revokeToken` instead of `getUser`.

Nearly weekend my friend :)

**Comment by fahadsadiq** [comment]
Fixed the issue.

**Review by ottokruse — APPROVED** [review]
Great, thanks again

**Comment by ottokruse** [comment]
Released in https://github.com/aws-samples/amazon-cognito-passwordless-auth/releases/tag/v0.13.2

**Pull request merged**
