### PR TITLE
Adding changes to deploy frontend on Windows and Mac

### PR DESCRIPTION
**Pull request by cordev-developer**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
Adding some changes to script "deploy-spa.cjs" and "package.json" files to deply the frontend on Windows and Mac.

### CODE REVIEW

**Comment by ottokruse** [comment]
Hey mate looks good but please run prettier :)

`npx prettier -w .`

**Comment by cordev-developer** [comment]
Hi Otto, I've executed prettier and I have pushed the new code, also I 've changed the script name in deploy-spa.cjs file. Let me know any further problem please.

**Comment by ottokruse** [comment]
Hey mate pettier is still complaining.

Can you double check?

```shell
npx prettier -c .
```

**Comment by cordev-developer** [comment]
Hi Otto, sorry, my bad, I'm not familiar with prettier and I've executed in a wrong way. Now I think it's all ok !

**Review by ottokruse — APPROVED** [review]

**Comment by ottokruse** [comment]
Thanks mate!

**Comment by cordev-developer** [comment]
It's a pleasure! Whatever it takes!

**Pull request merged**
