### PR TITLE
Add error documentation

### PR DESCRIPTION
**Pull request by tinti**
*Issue #, if available:*
n/a.

*Description of changes:*
Include a building option to avoid "Dynamic require of \"stream\" is not supported" error.

### CODE REVIEW

**Review by ottokruse — APPROVED** [review]

**Comment by ottokruse** [comment]
Thanks! Please run prettier and reformat the code and we're good

**Comment by ottokruse** [comment]
Still prettier is complaining. Can you run it like this from the root of the workspace?: `npx prettier -w .`

**Comment by ottokruse** [comment]
Sorry mate it's getting worse! The issue must be that you use another prettier config than the project. I see now that there is no prettier config in the project (which surprises me, didn't notice before), and I am not sure what is going on now ... looks like on your machine prettier finds another config file that you have.

Try this instead: `npx prettier --no-config -w .` That should skip your config.

We could add prettier config to this project to prevent this. Maybe add an empty prettier key in package.json (empty so we get all defaults): `prettier: {}`

**Comment by tinti** [comment]
No problem. Added.

I believe you already merged the code.

**Review by ottokruse — APPROVED** [review]

**Comment by ottokruse** [comment]
All done now. Thanks for your vigilance on our docs!

**Pull request merged**
